server:
  port: 9220

spring:
  application:
    name: cp-system
  profiles:
    active: dev
  cloud:
    nacos:
      server-addr: 192.168.253.132:8848
      username: nacos
      password: nacos
      discovery:
        enabled: true
        namespace: public
        register-enabled: true
      config:
        enabled: true
        group: DEFAULT_GROUP
        namespace: public
        file-extension: yml
  config:
    import:
      - optional:nacos:application-${spring.profiles.active}.yml
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.yml
      - optional:nacos:cp-security-${spring.profiles.active}.yml
